name: arbxcel
description: Generates ARB files from an Excel file or create an Excel file from ARB files.
version: 0.0.5
repository: https://github.com/iandis/arbxcel
issue_tracker: https://github.com/iandis/arbxcel/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.0
  excel: ^2.0.0-null-safety-3
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
